<script type="text/javascript">
    Payright.Installments.config = <?php echo json_encode($this->getJsConfig()) ?>;
    Payright.Installments.text = <?php echo json_encode($this->renderInstallments()); ?>;

    // console.log(Payright.Installments.text);
    // render installments amounts on dom:loaded event
    document.observe('dom:loaded', function () {
        Payright.Installments.render(Payright.Installments.text);
        // console.log(Payright.Installments.text);
    });

    jQuery(document).ready(function () {
        if (jQuery('div.modal-content').length > 0) {
            var modal = document.getElementById('payright_modal654');
            jQuery('.payright-what-is-modal-trigger').click(function (event) {
                jQuery('#payright_modal654').show();
            });
            jQuery('#PayrightHowitWorksmodalPopup > #close').click(function (event) {
                jQuery('#payright_modal654').hide();
            });
            window.onclick = function (event) {
                if (event.target == modal) {
                    jQuery('#payright_modal654').hide();
                }
            }
        }

        if (jQuery("body").has("[class*='related']")) {
            if (jQuery('[class*="related"]:has(div.payright)')) {
                // console.log("inside found");
                jQuery('[class*="related"] div.payright').hide();
            }
        }
        if (jQuery("body").has("[class*='upsell']")) {
            if (jQuery('[class*="upsell"]:has(div.payright)')) {
                // console.log("inside found");
                jQuery('[class*="upsell"] div.payright').hide();
            }
        }
    });
</script>
