<?php
$_code = $this->getMethodCode();
$installmentsArray = $this->fetchInstallments();
?>
<ul class="form-list" id="payment_form_<?php echo $_code ?>" style="display:none;">
    <li>
        <div class="payRight_container_cart">

            <article>
                <div class="payRight_columns installments">
                    <div class="insideColumns installments">
                        <Strong class="payRightH2 paymentstitle"
                                id="payrightmargin">
                            $<?php echo $installmentsArray['minDeposit'] . " today then "; ?>
                            <?php echo $installmentsArray['noofrepayments'] . " " . $installmentsArray['repaymentfrequency']; ?>
                            Installments of $<?php echo $installmentsArray['LoanAmountPerPayment']; ?></strong>
                    </div>
                </div>
            </article>

            <article>
                <div class="payRight_columns installments">
                    <div class="insideColumns payRight_is-8">
                        <p class="payRightPayment" id="payrightdeposit">You will be directed to the Payright website to
                            complete the application process.<br/>Once approved you will return to our page<br/>See <a
                                    href="https://www.payright.com.au/terms-of-use/" target=" ">Payright terms &
                                conditions</a> for further information.</p>
                    </div>
                </div>
            </article>

        </div>
    </li>
    <!-- <?php //if ($this->getInstructions()): ?>
    <li>
        <div class="<?php //echo $_code ?>-instructions-content agreement-content">
                <?php // echo nl2br($this->getInstructions()) ?>
        </div>
    </li>
<?php // endif; ?> -->
</ul>
