<?php
// Retrieve order
$_order = new Mage_Sales_Model_Order();
$orderId = Mage::getSingleton('checkout/session')->getLastRealOrderId();
$_order->loadByIncrementId($orderId);

?>
<form id="payrightgatewayform" name="payrightgatewayform" method="GET" action="<?php echo $this->builtAppendPoint; ?>">
    <input type="hidden" name="checkoutId" value="<?php echo $this->checkoutId; ?>">
    <input type="hidden" name="orderId" value="<?php echo $orderId; ?>">
</form>
<script type="text/javascript">
    document.payrightgatewayform.submit();
</script>