<?php
// Retrieve order
$_order = new Mage_Sales_Model_Order();
$orderId = Mage::getSingleton('checkout/session')->getLastRealOrderId();
$_order->loadByIncrementId($orderId);

?>
<form id="payrightgatewayform" name="payrightgatewayform" method="GET" action="<?php echo $this->builtappendpoint; ?>">
    <input type="hidden" name="checkoutid" value="<?php echo $this->checkoutid; ?>">
    <input type="hidden" name="orderid" value="<?php echo $this->orderId; ?>">
</form>
<script type="text/javascript">
    document.payrightgatewayform.submit();
</script>